added segmentation model
camicroscope/tfjs-models pull request #3
Opened 2020-07-17 23:26 UTC by leoarc

## Description
Added YNet model

## Motivation and Context
Expand model set

## Types of changes
**What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
**Go over all the following points, and put an `x` in all the boxes that apply.
**(If you're unsure about any of these, don't hesitate to ask. We're here to help!)
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-07-21 07:34 UTC, Insiyaa requested changes
Add about image preprocessing, I really like the format you used [here](https://github.com/camicroscope/tfjs-models/tree/master/Classification%20Sample%20Models/ICIAR18_data_IRRCNN_model).

2020-07-21 07:34 UTC, Insiyaa commented on Segmentation Sample Models/YNet/README.md
> +A total of 87 pathologists diagnosed a randomly assigned subset of 60 slides into four diagnostic categories (benign, atypia, ductal carcinomain situ, and invasive cancer),producing an average of 22
Highlight the categories, that is don't put in parenthesis as it is a required field while uploading. Also, mention the magnification of samples.

2020-07-22 06:09 UTC, Insiyaa commented
Great! Please add a link to the model in the readme of the repository.

2020-07-22 21:49 UTC, leoarc commented
Sorry for not including everything in one go. Please let me know if I missed something again.

2020-07-23 04:18 UTC, birm approved these changes
I think this is a good addition. Of course, I'll wait for @Insiyaa to approve before merging, but I do have a light suggestion; the ipnb file committed looks like it wasn't run. Does it make sense to commit a version which was run and has output?

2020-07-23 12:34 UTC, leoarc commented
I have added the executed file except the train cell as that would take very long.Is the ok ?

2020-07-24 07:46 UTC, Insiyaa approved these changes
Looks good!

2020-07-24 13:50 UTC, merged